### ISSUE TITLE
上传覆盖

### ISSUE THREAD

**Issue by cismous** [polym/upx#14]
使用 upx put file 不会覆盖之前的文件吗，通过 upx put --help 也未看到详细的参数详解

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by polym** [comment]
put 会覆盖之前的文件的。CDN 刷新可能需要一定的时间。您可以 ls 看下文件的修改时间或者大小这些信息有没有改变

**Comment by cismous** [comment]
不至于回复我这么多遍吧

我就是通过ls看了，时间没有改变，然后就删除了之前了，再重新put就可以了，所以我想知道是否不需要我删除，直接覆盖

**Comment by polym** [comment]
不好意思，刚才家里网太烂了，回复了多次。`put` 是直接覆盖的。如果还出现这个问题，可以提供一些具体信息，我这边排查下

**Comment by cismous** [comment]
既然是覆盖的，重新put后，ls 查看到的文件列表，时间没有变化呢

**Comment by polym** [comment]
对，这个问题需要具体分析下，理论上不可能出现这样的问题

**Comment by polym** [comment]
暂时先关闭了
