### ISSUE TITLE
upx sync 的返回值问题

### ISSUE THREAD

**Issue by qious** [polym/upx#15]
写了一个 GitLab CI ，在 CI 的最后是将编译产生的文件同步到 UPYUN，但在同步时候可能因为某些原因出错，这是在所难免的，但是不知能不能当 fails 不为 0 时 os.Exit(-1)  之类的？

![image](https://cloud.githubusercontent.com/assets/10327533/20820166/34ea7b32-b874-11e6-96e0-90c916a3e642.png)

**Comment by polym** [comment]
@qious 很好的建议，最近我会花时间优化下。

**Comment by polym** [comment]
已经增加这个判断逻辑 https://github.com/polym/upx/pull/16/files#diff-8395fa844bc4d2e33f3cccb63de5a32aR212

**Comment by qious** [comment]
谢谢，辛苦了
