### ISSUE TITLE
如果能自己控制put线程的话～

### ISSUE THREAD

**Issue by hoythan** [polym/upx#30]
现在的上传线程好像固定5个，文件有十几GB，服务器带宽也足够，上传虽然很快，但是也很"慢"

**Comment by polym** [comment]
可以用 `-w` 参数可以指定并发个数，这个是否可以满足你的需求？

**Comment by polym** [comment]
上传文件较多的时候，建议使用  `upx sync`，避免文件多次上传。

**Comment by hoythan** [comment]
哦哦 ，不好意思我还以为只能增量同步中使用。多谢。
