### ISSUE TITLE
上传支持

### ISSUE THREAD

**Issue by cismous** [polym/upx#8]
上传的时候可以支持通配符 * 的方式上传一个文件夹下的所有文件吗？

**Comment by polym** [comment]
上传暂时还不支持通配符。文件夹可以直接上传，`upx put /path/to/dir1 dir2`。不过这种方式会上传到 `dir2/dir1` 下的。这个之后可以支持下

**Comment by cismous** [comment]
可能是因为我之前用过七牛，受到影响吧
因为我只是希望上传我所有的文件到根目录，对于这个需求，你有什么好的建议吗

**Comment by polym** [comment]
可以使用 `upx sync` 将本地目录的文件同步到又拍云
